using System.Collections.Generic;
using static StarLoop.Script.Cell;
namespace StarLoop.Script;

public enum Cell : byte
{
    Air,
    Wire,
    RedHead,
    RedTail,
    GreenHead,
    GreenTail,
    BlueHead,
    BlueTail,
    CyanHead,
    CyanTail,
    MagentaHead,
    MagentaTail,
    YellowHead,
    YellowTail,
    WhiteHead,
    WhiteTail,
    
    TodoTile1,
    WireDecay1,
    RedHeadDecay1,
    RedTailDecay1,
    GreenHeadDecay1,
    GreenTailDecay1,
    BlueHeadDecay1,
    BlueTailDecay1,
    CyanHeadDecay1,
    CyanTailDecay1,
    MagentaHeadDecay1,
    MagentaTailDecay1,
    YellowHeadDecay1,
    YellowTailDecay1,
    WhiteHeadDecay1,
    WhiteTailDecay1,
    
    TodoTile2,
    WireDecay2,
    RedHeadDecay2,
    RedTailDecay2,
    GreenHeadDecay2,
    GreenTailDecay2,
    BlueHeadDecay2,
    BlueTailDecay2,
    CyanHeadDecay2,
    CyanTailDecay2,
    MagentaHeadDecay2,
    MagentaTailDecay2,
    YellowHeadDecay2,
    YellowTailDecay2,
    WhiteHeadDecay2,
    WhiteTailDecay2,
    
    TodoTile3,
    WireDecay3,
    RedHeadDecay3,
    RedTailDecay3,
    GreenHeadDecay3,
    GreenTailDecay3,
    BlueHeadDecay3,
    BlueTailDecay3,
    CyanHeadDecay3,
    CyanTailDecay3,
    MagentaHeadDecay3,
    MagentaTailDecay3,
    YellowHeadDecay3,
    YellowTailDecay3,
    WhiteHeadDecay3,
    WhiteTailDecay3,
    
    TodoTile4,
    WireDecay4,
    RedHeadDecay4,
    RedTailDecay4,
    GreenHeadDecay4,
    GreenTailDecay4,
    BlueHeadDecay4,
    BlueTailDecay4,
    CyanHeadDecay4,
    CyanTailDecay4,
    MagentaHeadDecay4,
    MagentaTailDecay4,
    YellowHeadDecay4,
    YellowTailDecay4,
    WhiteHeadDecay4,
    WhiteTailDecay4,
    
    TodoTile5,
    RedFilter,
    RedFilterRedHead,
    RedFilterRedTail,
    RedFilterDecay1,
    RedFilterRedHeadDecay1,
    RedFilterRedTailDecay1,
    RedFilterDecay2,
    RedFilterRedHeadDecay2,
    RedFilterRedTailDecay2,
    RedFilterDecay3,
    RedFilterRedHeadDecay3,
    RedFilterRedTailDecay3,
    RedFilterDecay4,
    RedFilterRedHeadDecay4,
    RedFilterRedTailDecay4,
    
    TodoTile6,
    GreenFilter,
    GreenFilterGreenHead,
    GreenFilterGreenTail,
    GreenFilterDecay1,
    GreenFilterGreenHeadDecay1,
    GreenFilterGreenTailDecay1,
    GreenFilterDecay2,
    GreenFilterGreenHeadDecay2,
    GreenFilterGreenTailDecay2,
    GreenFilterDecay3,
    GreenFilterGreenHeadDecay3,
    GreenFilterGreenTailDecay3,
    GreenFilterDecay4,
    GreenFilterGreenHeadDecay4,
    GreenFilterGreenTailDecay4,
    
    TodoTile7,
    BlueFilter,
    BlueFilterBlueHead,
    BlueFilterBlueTail,
    BlueFilterDecay1,
    BlueFilterBlueHeadDecay1,
    BlueFilterBlueTailDecay1,
    BlueFilterDecay2,
    BlueFilterBlueHeadDecay2,
    BlueFilterBlueTailDecay2,
    BlueFilterDecay3,
    BlueFilterBlueHeadDecay3,
    BlueFilterBlueTailDecay3,
    BlueFilterDecay4,
    BlueFilterBlueHeadDecay4,
    BlueFilterBlueTailDecay4,
    
    TodoTile8,
    CyanFilter,
    CyanFilterCyanHead,
    CyanFilterCyanTail,
    CyanFilterDecay1,
    CyanFilterCyanHeadDecay1,
    CyanFilterCyanTailDecay1,
    CyanFilterDecay2,
    CyanFilterCyanHeadDecay2,
    CyanFilterCyanTailDecay2,
    CyanFilterDecay3,
    CyanFilterCyanHeadDecay3,
    CyanFilterCyanTailDecay3,
    CyanFilterDecay4,
    CyanFilterCyanHeadDecay4,
    CyanFilterCyanTailDecay4,
    
    TodoTile9,
    MagentaFilter,
    MagentaFilterMagentaHead,
    MagentaFilterMagentaTail,
    MagentaFilterDecay1,
    MagentaFilterMagentaHeadDecay1,
    MagentaFilterMagentaTailDecay1,
    MagentaFilterDecay2,
    MagentaFilterMagentaHeadDecay2,
    MagentaFilterMagentaTailDecay2,
    MagentaFilterDecay3,
    MagentaFilterMagentaHeadDecay3,
    MagentaFilterMagentaTailDecay3,
    MagentaFilterDecay4,
    MagentaFilterMagentaHeadDecay4,
    MagentaFilterMagentaTailDecay4,
    
    TodoTile10,
    YellowFilter,
    YellowFilterYellowHead,
    YellowFilterYellowTail,
    YellowFilterDecay1,
    YellowFilterYellowHeadDecay1,
    YellowFilterYellowTailDecay1,
    YellowFilterDecay2,
    YellowFilterYellowHeadDecay2,
    YellowFilterYellowTailDecay2,
    YellowFilterDecay3,
    YellowFilterYellowHeadDecay3,
    YellowFilterYellowTailDecay3,
    YellowFilterDecay4,
    YellowFilterYellowHeadDecay4,
    YellowFilterYellowTailDecay4,
    
    CyanFilterGreenHead,
    CyanFilterGreenTail,
    CyanFilterGreenHeadDecay1,
    CyanFilterGreenTailDecay1,
    CyanFilterGreenHeadDecay2,
    CyanFilterGreenTailDecay2,
    CyanFilterGreenHeadDecay3,
    CyanFilterGreenTailDecay3,
    CyanFilterGreenHeadDecay4,
    CyanFilterGreenTailDecay4,
    YellowFilterRedHead,
    YellowFilterRedTail,
    YellowFilterRedHeadDecay2,
    YellowFilterRedTailDecay2,
    YellowFilterRedHeadDecay4,
    YellowFilterRedTailDecay4,
    
    CyanFilterBlueHead,
    CyanFilterBlueTail,
    CyanFilterBlueHeadDecay1,
    CyanFilterBlueTailDecay1,
    CyanFilterBlueHeadDecay2,
    CyanFilterBlueTailDecay2,
    CyanFilterBlueHeadDecay3,
    CyanFilterBlueTailDecay3,
    CyanFilterBlueHeadDecay4,
    CyanFilterBlueTailDecay4,
    YellowFilterGreenHead,
    YellowFilterGreenTail,
    YellowFilterGreenHeadDecay2,
    YellowFilterGreenTailDecay2,
    YellowFilterGreenHeadDecay4,
    YellowFilterGreenTailDecay4,
    
    MagentaFilterRedHead,
    MagentaFilterRedTail,
    MagentaFilterRedHeadDecay1,
    MagentaFilterRedTailDecay1,
    MagentaFilterRedHeadDecay2,
    MagentaFilterRedTailDecay2,
    MagentaFilterRedHeadDecay3,
    MagentaFilterRedTailDecay3,
    MagentaFilterRedHeadDecay4,
    MagentaFilterRedTailDecay4,
    YellowFilterRedHeadDecay1,
    YellowFilterRedTailDecay1,
    YellowFilterRedHeadDecay3,
    YellowFilterRedTailDecay3,
    TodoTile11,
    TodoTile12,
    
    MagentaFilterBlueHead,
    MagentaFilterBlueTail,
    MagentaFilterBlueHeadDecay1,
    MagentaFilterBlueTailDecay1,
    MagentaFilterBlueHeadDecay2,
    MagentaFilterBlueTailDecay2,
    MagentaFilterBlueHeadDecay3,
    MagentaFilterBlueTailDecay3,
    MagentaFilterBlueHeadDecay4,
    MagentaFilterBlueTailDecay4,
    YellowFilterGreenHeadDecay1,
    YellowFilterGreenTailDecay1,
    YellowFilterGreenHeadDecay3,
    YellowFilterGreenTailDecay3,
    TodoTile13,
    TodoTile14,
    
    Text1,
    Text2,
    Text3,
    Text4,
    Text5,
    Text6,
    Text7,
    Text8,
    Text9,
    Text10,
    Text11,
    Text12,
    Text13,
    Text14,
    Text15,
    Text16,
}
public static class TransitionRules
{
    private static Rule[] Always => System.Array.Empty<Rule>();
    public static readonly List<WireworldTransition> Transitions = new List<WireworldTransition>()
    {
        //basic transitions
        new(new Rule[] { new(RedHead, 1, 2) }, Wire, RedHead),
        new(Always, RedHead, RedTail), 
        new(Always, RedTail, Wire),
        new(new Rule[] { new(GreenHead, 1, 2) }, Wire, GreenHead),
        new(Always, GreenHead, GreenTail),
        new(Always, GreenTail, Wire), 
        new(new Rule[] { new(BlueHead, 1, 2) }, Wire, BlueHead),
        new(Always, BlueHead, BlueTail),
        new(Always, BlueTail, Wire),
        new(new Rule[] { new(CyanHead, 1, 2) }, Wire, CyanHead),
        new(Always, CyanHead, CyanTail), 
        new(Always, CyanTail, Wire),
        new(new Rule[] { new(MagentaHead, 1, 2) }, Wire, MagentaHead),
        new(Always, MagentaHead, MagentaTail),
        new(Always, MagentaTail, Wire), 
        new(new Rule[] { new(YellowHead, 1, 2) }, Wire, YellowHead),
        new(Always, YellowHead, YellowTail),
        new(Always, YellowTail, Wire),
        new(new Rule[] { new(WhiteHead, 1, 2) }, Wire, WhiteHead),
        new(Always, WhiteHead, WhiteTail),
        new(Always, WhiteTail, Wire),
        
        //merging signals
        new(new Rule[] { new(GreenHead, 1, 2),new(BlueHead, 1, 2) }, Wire, CyanHead),
        new(new Rule[] { new(RedHead, 1, 2),new(BlueHead, 1, 2) }, Wire, MagentaHead),
        new(new Rule[] { new(RedHead, 1, 2),new(GreenHead, 1, 2) }, Wire, YellowHead),
        new(new Rule[] { new(RedHead, 1, 2),new(CyanHead, 1, 2) }, Wire, WhiteHead),
        new(new Rule[] { new(GreenHead, 1, 2),new(MagentaHead, 1, 2) }, Wire, WhiteHead),
        new(new Rule[] { new(BlueHead, 1, 2),new(YellowHead, 1, 2) }, Wire, WhiteHead),
        
        //Filtering signals
        new(new Rule[] { new(RedFilterRedHead, 1, 2)}, Wire, RedHead),
        //filters
        new(new Rule[] { new(WhiteHead, 1, 2)}, RedFilter, RedFilterRedHead),
        //Decay states
        new(new Rule[] { new(RedHead, 1, 2,0.8f) }, WireDecay1, RedHeadDecay1),
        new(Always, RedHeadDecay1, RedTailDecay1), 
        new(Always, RedTailDecay1, WireDecay1),
        //Decay progression
        
        new(new Rule[] { new(RedHeadDecay1, 1, 2,0.99f) }, Wire, RedHead),
        new(new Rule[] { new(RedHeadDecay1, 1, 2,0.01f) }, Wire, RedHead),
    };
}